name = "nazuaf-news"
main = "src/index.js"
compatibility_date = "2026-10-08"

[vars]
SITE_NAME = "Nazuaf News"

[[d1_databases]]
binding = "DB"
database_name = "nazuaf-news"
database_id = "bc282965-848b-4e08-9409-ffa2bc693859"

[triggers]
crons = ["0 */3 * * *"]
